[package]
authors = ["Ricardo Pieper <ricardopieper@live.com>"]
name = "sudoku"
version = "0.1.0"
[dependencies]
piston = "*"
piston2d-graphics = "*"
piston2d-opengl_graphics = "*"
pistoncore-glutin_window = "*"
